import { MD3LightTheme } from 'react-native-paper';

export const MaterialTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#3B6939',
    onPrimary: '#ffffff',
    primaryContainer: '#BCF0B4',
    onPrimaryContainer: '#235024',
    secondary: '#27638A',
    onSecondary: '#ffffff',
    secondaryContainer: '#CAE6FF',
    onSecondaryContainer: '#004B70',
    tertiary: '#7B4E7F',
    onTertiary: '#ffffff',
    tertiaryContainer: '#FFD6FE',
    onTertiaryContainer: '#613766',
    error: '#904A45',
    onError: '#ffffff',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#73332F',
    background: '#F7FBF1',
    onBackground: '#191D17',
    surface: '#F5FAFB',
    onSurface: '#171D1E',
    surfaceVariant: '#DBE4E6',
    onSurfaceVariant: '#3F484A',
    outline: '#6F797A',
    outlineVariant: '#BFC8CA',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2B3133',
    inverseOnSurface: '#ECF2F3',
    inversePrimary: '#A1D39A',
    elevation: {
      level0: 'transparent',
      level1: '#f4f8fb',
      level2: '#edf3f8',
      level3: '#e5eef4',
      level4: '#e3ecf1',
      level5: '#dfe8ef',
    },
  },
};